# Generated by Django 4.0.2 on 2022-02-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacuums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.FilePathField(default='default.png', path='/img'),
        ),
    ]
